/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	v1alpha1 "p4kube/pkg/apis/p4kube/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeP4s implements P4Interface
type FakeP4s struct {
	Fake *FakeP4kubeV1alpha1
	ns   string
}

var p4sResource = v1alpha1.SchemeGroupVersion.WithResource("p4s")

var p4sKind = v1alpha1.SchemeGroupVersion.WithKind("P4")

// Get takes name of the p4, and returns the corresponding p4 object, and an error if there is any.
func (c *FakeP4s) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.P4, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(p4sResource, c.ns, name), &v1alpha1.P4{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.P4), err
}

// List takes label and field selectors, and returns the list of P4s that match those selectors.
func (c *FakeP4s) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.P4List, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(p4sResource, p4sKind, c.ns, opts), &v1alpha1.P4List{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.P4List{ListMeta: obj.(*v1alpha1.P4List).ListMeta}
	for _, item := range obj.(*v1alpha1.P4List).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested p4s.
func (c *FakeP4s) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(p4sResource, c.ns, opts))

}

// Create takes the representation of a p4 and creates it.  Returns the server's representation of the p4, and an error, if there is any.
func (c *FakeP4s) Create(ctx context.Context, p4 *v1alpha1.P4, opts v1.CreateOptions) (result *v1alpha1.P4, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(p4sResource, c.ns, p4), &v1alpha1.P4{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.P4), err
}

// Update takes the representation of a p4 and updates it. Returns the server's representation of the p4, and an error, if there is any.
func (c *FakeP4s) Update(ctx context.Context, p4 *v1alpha1.P4, opts v1.UpdateOptions) (result *v1alpha1.P4, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(p4sResource, c.ns, p4), &v1alpha1.P4{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.P4), err
}

// Delete takes name of the p4 and deletes it. Returns an error if one occurs.
func (c *FakeP4s) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(p4sResource, c.ns, name, opts), &v1alpha1.P4{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeP4s) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(p4sResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.P4List{})
	return err
}

// Patch applies the patch and returns the patched p4.
func (c *FakeP4s) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.P4, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(p4sResource, c.ns, name, pt, data, subresources...), &v1alpha1.P4{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.P4), err
}
