- Install go; wget https://go.dev/dl/go1.20.5.linux-amd64.tar.gz
- sudo apt-get remove golang-go && sudo rm -rf /usr/local/go/

- sudo tar -C /usr/local -xzf go1.20.5.linux-amd64.tar.gz 
- export PATH=$PATH:/usr/local/go/bin
- go version
- cd /home/$(whoami)/p4kube 
- go get .
- kubectl create namespace p4-namespace
- kubectl create -f home/$(whoami)/p4kube/manifests/p4-crds.yaml 
- To list created p4resources, `kubectl get p4s -n p4-namespace`
- To see, all details of p4 resource, `kubectl get p4s -n p4-namespace testuhabiba2-p4 -oyaml`
