apiVersion: "p4kube.comnets/v1alpha1"
kind: P4
metadata:
  name: l2fwd-run
  namespace: p4-namespace
spec:
  networkFunction: "l2fwd"
  deploymentPhase: "switch-compilation"
  p4ProgramLocation: "./examples/l2fwd-gen.p4 "
  compilerDirectory: "/home/$(whoami)/t4p4s"
  compilerCommand: "./t4p4s.sh run model=v1model"
  