apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: p4s.p4kube.comnets.com
spec:
  group: p4kube.comnets.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                p4ProgramLocation:
                  type: string
                compilerCommand:
                  type: string
                replicas:
                  type: integer
                  minimum: 1
              required: ["p4ProgramLocation", "compilerCommand"]
          required: ["spec"]
  scope: Namespaced
  names:
    plural: p4s
    singular: p4
    kind: P4
    shortNames:
    - p4
