apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: p4s.p4kube.comnets
spec:
  group: p4kube.comnets
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                p4ProgramLocation:
                  type: string
                compilerDirectory:
                  type: string
                replicas:
                  type: integer
                  minimum: 1
              required: ["p4ProgramLocation", "compilerDirectory"]
            status:
              type: object
              properties:
                progress:
                  type: string
          required: ["spec"]
      subresources:
        status: {}
  names:
    plural: p4s
    singular: p4
    kind: P4
    shortNames:
    - p4
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
