apiVersion: "p4kube.comnets/v1alpha1"
kind: P4
metadata:
  name: testuhabiba2-p4
  namespace: p4-namespace
spec:
  p4ProgramLocation: "./examples/l2fwd-gen.p4"
  compilerDirectory: "/home/$(whoami)/t4p4s"
  replicas: 2
