/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	json "encoding/json"
	"fmt"
	v1alpha1 "p4kube/pkg/apis/p4kube/v1alpha1"
	p4kubev1alpha1 "p4kube/pkg/client/applyconfiguration/p4kube/v1alpha1"
	scheme "p4kube/pkg/client/clientset/versioned/scheme"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// P4sGetter has a method to return a P4Interface.
// A group's client should implement this interface.
type P4sGetter interface {
	P4s(namespace string) P4Interface
}

// P4Interface has methods to work with P4 resources.
type P4Interface interface {
	Create(ctx context.Context, p4 *v1alpha1.P4, opts v1.CreateOptions) (*v1alpha1.P4, error)
	Update(ctx context.Context, p4 *v1alpha1.P4, opts v1.UpdateOptions) (*v1alpha1.P4, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.P4, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.P4List, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.P4, err error)
	Apply(ctx context.Context, p4 *p4kubev1alpha1.P4ApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.P4, err error)
	P4Expansion
}

// p4s implements P4Interface
type p4s struct {
	client rest.Interface
	ns     string
}

// newP4s returns a P4s
func newP4s(c *P4kubeV1alpha1Client, namespace string) *p4s {
	return &p4s{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the p4, and returns the corresponding p4 object, and an error if there is any.
func (c *p4s) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.P4, err error) {
	result = &v1alpha1.P4{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("p4s").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of P4s that match those selectors.
func (c *p4s) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.P4List, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.P4List{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("p4s").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested p4s.
func (c *p4s) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("p4s").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a p4 and creates it.  Returns the server's representation of the p4, and an error, if there is any.
func (c *p4s) Create(ctx context.Context, p4 *v1alpha1.P4, opts v1.CreateOptions) (result *v1alpha1.P4, err error) {
	result = &v1alpha1.P4{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("p4s").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(p4).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a p4 and updates it. Returns the server's representation of the p4, and an error, if there is any.
func (c *p4s) Update(ctx context.Context, p4 *v1alpha1.P4, opts v1.UpdateOptions) (result *v1alpha1.P4, err error) {
	result = &v1alpha1.P4{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("p4s").
		Name(p4.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(p4).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the p4 and deletes it. Returns an error if one occurs.
func (c *p4s) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("p4s").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *p4s) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("p4s").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched p4.
func (c *p4s) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.P4, err error) {
	result = &v1alpha1.P4{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("p4s").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied p4.
func (c *p4s) Apply(ctx context.Context, p4 *p4kubev1alpha1.P4ApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.P4, err error) {
	if p4 == nil {
		return nil, fmt.Errorf("p4 provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(p4)
	if err != nil {
		return nil, err
	}
	name := p4.Name
	if name == nil {
		return nil, fmt.Errorf("p4.Name must be provided to Apply")
	}
	result = &v1alpha1.P4{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("p4s").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
