apiVersion: "p4kube.comnets/v1alpha1"
kind: P4
metadata:
  name: firewall-c
  namespace: p4-namespace
spec:
  networkFunction: "firewall"
  deploymentPhase: "c-compilation"
  p4ProgramLocation: "./examples/firewall.p4"
  compilerDirectory: "/home/$(whoami)/t4p4s"
  compilerCommand: "./t4p4s.sh p4 c model=v1model"
