/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	p4kubev1alpha1 "p4kube/pkg/apis/p4kube/v1alpha1"
	versioned "p4kube/pkg/client/clientset/versioned"
	internalinterfaces "p4kube/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "p4kube/pkg/client/listers/p4kube/v1alpha1"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// P4Informer provides access to a shared informer and lister for
// P4s.
type P4Informer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.P4Lister
}

type p4Informer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewP4Informer constructs a new informer for P4 type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewP4Informer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredP4Informer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredP4Informer constructs a new informer for P4 type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredP4Informer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.P4kubeV1alpha1().P4s(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.P4kubeV1alpha1().P4s(namespace).Watch(context.TODO(), options)
			},
		},
		&p4kubev1alpha1.P4{},
		resyncPeriod,
		indexers,
	)
}

func (f *p4Informer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredP4Informer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *p4Informer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&p4kubev1alpha1.P4{}, f.defaultInformer)
}

func (f *p4Informer) Lister() v1alpha1.P4Lister {
	return v1alpha1.NewP4Lister(f.Informer().GetIndexer())
}
