// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.12.1
// source: p4kube_grpc/p4kube_grpc.proto

package p4kube

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the p4resource's details.
type P4Resource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Command string `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
}

func (x *P4Resource) Reset() {
	*x = P4Resource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p4kube_grpc_p4kube_grpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *P4Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P4Resource) ProtoMessage() {}

func (x *P4Resource) ProtoReflect() protoreflect.Message {
	mi := &file_p4kube_grpc_p4kube_grpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P4Resource.ProtoReflect.Descriptor instead.
func (*P4Resource) Descriptor() ([]byte, []int) {
	return file_p4kube_grpc_p4kube_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *P4Resource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *P4Resource) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

// The response message containing status of P4 deployment.
type DeploymentStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *DeploymentStatus) Reset() {
	*x = DeploymentStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p4kube_grpc_p4kube_grpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeploymentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentStatus) ProtoMessage() {}

func (x *DeploymentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_p4kube_grpc_p4kube_grpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentStatus.ProtoReflect.Descriptor instead.
func (*DeploymentStatus) Descriptor() ([]byte, []int) {
	return file_p4kube_grpc_p4kube_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *DeploymentStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_p4kube_grpc_p4kube_grpc_proto protoreflect.FileDescriptor

var file_p4kube_grpc_p4kube_grpc_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x34, 0x6b, 0x75, 0x62, 0x65, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x34,
	0x6b, 0x75, 0x62, 0x65, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0b, 0x70, 0x34, 0x6b, 0x75, 0x62, 0x65, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x22, 0x3a, 0x0a, 0x0a,
	0x50, 0x34, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x2a, 0x0a, 0x10, 0x44, 0x65, 0x70, 0x6c,
	0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x32, 0x5d, 0x0a, 0x13, 0x50, 0x34, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x46, 0x0a, 0x08, 0x44,
	0x65, 0x70, 0x6c, 0x6f, 0x79, 0x50, 0x34, 0x12, 0x17, 0x2e, 0x70, 0x34, 0x6b, 0x75, 0x62, 0x65,
	0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x34, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x1a, 0x1d, 0x2e, 0x70, 0x34, 0x6b, 0x75, 0x62, 0x65, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x44,
	0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0x00, 0x30, 0x01, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x70, 0x34, 0x6b, 0x75, 0x62, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_p4kube_grpc_p4kube_grpc_proto_rawDescOnce sync.Once
	file_p4kube_grpc_p4kube_grpc_proto_rawDescData = file_p4kube_grpc_p4kube_grpc_proto_rawDesc
)

func file_p4kube_grpc_p4kube_grpc_proto_rawDescGZIP() []byte {
	file_p4kube_grpc_p4kube_grpc_proto_rawDescOnce.Do(func() {
		file_p4kube_grpc_p4kube_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_p4kube_grpc_p4kube_grpc_proto_rawDescData)
	})
	return file_p4kube_grpc_p4kube_grpc_proto_rawDescData
}

var file_p4kube_grpc_p4kube_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_p4kube_grpc_p4kube_grpc_proto_goTypes = []interface{}{
	(*P4Resource)(nil),       // 0: p4kube_grpc.P4Resource
	(*DeploymentStatus)(nil), // 1: p4kube_grpc.DeploymentStatus
}
var file_p4kube_grpc_p4kube_grpc_proto_depIdxs = []int32{
	0, // 0: p4kube_grpc.P4DeploymentService.DeployP4:input_type -> p4kube_grpc.P4Resource
	1, // 1: p4kube_grpc.P4DeploymentService.DeployP4:output_type -> p4kube_grpc.DeploymentStatus
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_p4kube_grpc_p4kube_grpc_proto_init() }
func file_p4kube_grpc_p4kube_grpc_proto_init() {
	if File_p4kube_grpc_p4kube_grpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_p4kube_grpc_p4kube_grpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*P4Resource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p4kube_grpc_p4kube_grpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeploymentStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_p4kube_grpc_p4kube_grpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_p4kube_grpc_p4kube_grpc_proto_goTypes,
		DependencyIndexes: file_p4kube_grpc_p4kube_grpc_proto_depIdxs,
		MessageInfos:      file_p4kube_grpc_p4kube_grpc_proto_msgTypes,
	}.Build()
	File_p4kube_grpc_p4kube_grpc_proto = out.File
	file_p4kube_grpc_p4kube_grpc_proto_rawDesc = nil
	file_p4kube_grpc_p4kube_grpc_proto_goTypes = nil
	file_p4kube_grpc_p4kube_grpc_proto_depIdxs = nil
}
