apiVersion: "p4kube.comnets/v1alpha1"
kind: P4
metadata:
  name: portfwd-p4
  namespace: p4-namespace
spec:
  networkFunction: "portfwd"
  deploymentPhase: "p4-conversion"
  p4ProgramLocation: "./examples/portfwd-gen.p4"
  compilerDirectory: "/home/$(whoami)/t4p4s"
  compilerCommand: "./t4p4s.sh p4 model=v1model"
