apiVersion: "p4kube.comnets/v1alpha1"
kind: P4
metadata:
  name: portfwd-c
  namespace: p4-namespace
spec:
  networkFunction: "portfwd"
  deploymentPhase: "c-compilation"
  p4ProgramLocation: "./examples/portfwd-gen.p4"
  compilerDirectory: "/home/$(whoami)/t4p4s"
  compilerCommand: "./t4p4s.sh c model=v1model"
