apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:6.2.1-apache
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_NAME
          valueFrom:
                secretKeyRef: 
                  name: mysql-secret
                  key: mysql-database
        - name: WORDPRESS_DB_USER
          valueFrom:
                secretKeyRef: 
                  name: mysql-secret
                  key: mysql-username

        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
                secretKeyRef: 
                  name: mysql-secret
                  key: mysql-password

        - name: WORDPRESS_DB_HOST
          valueFrom: 
            configMapKeyRef:
              name: mysql-configmap
              key: mysqldb-url
      nodeSelector:
        p4kube: applications
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    app: wordpress
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
    nodePort: 30001
    protocol: TCP

